import { PrismaClient, Prisma } from '@prisma/client';
import { resolveAccount } from './account-resolver';
import { TransactionSource } from '@prisma/client';

export type JournalParams = {
  reference: string;
  note?: string;
  sourceId?: string;
  entries: {
    accountCode: string;
    debit: number;
    credit: number;
    description?: string;
  }[];
  date?: Date;
};

async function generateUniqueEntryNumber(tx: Prisma.TransactionClient, date: Date): Promise<string> {
  const yearMonth = `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, '0')}`;
  
  let attempts = 0;
  while (attempts < 3) {
    const lastEntry = await tx.journalEntry.findFirst({
      where: { entryNumber: { startsWith: `JE-${yearMonth}-` } },
      orderBy: { entryNumber: 'desc' },
      select: { entryNumber: true }
    });

    let sequence = 1;
    if (lastEntry) {
      const lastSeq = parseInt(lastEntry.entryNumber.split('-')[2], 10);
      if (!isNaN(lastSeq)) sequence = lastSeq + 1;
    }
    
    sequence += attempts;
    const entryNumber = `JE-${yearMonth}-${String(sequence).padStart(4, '0')}`;
    
    const exists = await tx.journalEntry.findUnique({
      where: { entryNumber },
      select: { id: true }
    });

    if (!exists) return entryNumber;
    attempts++;
  }
  
  throw new Error("Could not generate a unique Journal Entry number after 3 attempts.");
}

/**
 * Creates an auto-generated double-entry journal within a Prisma transaction.
 * Ensures that debits strictly equal credits.
 */
export async function createAutoJournalEntry(
  tx: Prisma.TransactionClient,
  source: TransactionSource,
  params: JournalParams
) {
  // 1. Validate Debits = Credits (with 2 decimal precision rounding)
  const totalDebit = Math.round(params.entries.reduce((sum, e) => sum + e.debit, 0) * 100) / 100;
  const totalCredit = Math.round(params.entries.reduce((sum, e) => sum + e.credit, 0) * 100) / 100;

  if (Math.abs(totalDebit - totalCredit) > 0.001) {
    throw new Error(`Accounting error: Debits (${totalDebit}) do not equal Credits (${totalCredit}) for reference ${params.reference}`);
  }

  // 2. Generate Entry Number safely
  const now = params.date || new Date();
  const entryNumber = await generateUniqueEntryNumber(tx, now);

  // 3. Resolve Account IDs
  const resolvedEntries = await Promise.all(
    params.entries.map(async (entry) => {
      const accountId = await resolveAccount(entry.accountCode, tx);
      return {
        accountId,
        debit: entry.debit,
        credit: entry.credit,
        description: entry.description,
      };
    })
  );

  // 4. Create Journal Entry
  const je = await tx.journalEntry.create({
    data: {
      entryNumber,
      date: now,
      reference: params.reference,
      note: params.note,
      source,
      sourceId: params.sourceId,
      isAutoGenerated: true,
      journalEntryItems: {
        create: resolvedEntries
      }
    },
    include: {
      journalEntryItems: true
    }
  });

  // 5. Update Account Balances
  for (const entry of resolvedEntries) {
    const account = await tx.chartOfAccount.findUnique({ where: { id: entry.accountId } });
    if (!account) continue;

    let balanceChange = 0;
    if (['ASSET', 'EXPENSE', 'COGS'].includes(account.type)) {
      balanceChange = entry.debit - entry.credit;
    } else {
      balanceChange = entry.credit - entry.debit;
    }

    if (balanceChange !== 0) {
      const updated = await tx.chartOfAccount.update({
        where: { id: entry.accountId },
        data: { balance: { increment: balanceChange } }
      });
      
      const rounded = Math.round(updated.balance * 100) / 100;
      if (updated.balance !== rounded) {
        await tx.chartOfAccount.update({
          where: { id: entry.accountId },
          data: { balance: rounded }
        });
      }
    }
  }

  return je;
}

/**
 * Creates a Contra-Entry (Reversal) for a given Journal Entry.
 * This ensures the ledger remains immutable while correcting mistakes (like returns/cancellations).
 */
export async function createContraEntry(
  tx: Prisma.TransactionClient,
  originalEntryNumber: string,
  reason: string,
  date?: Date
) {
  const original = await tx.journalEntry.findUnique({
    where: { entryNumber: originalEntryNumber },
    include: { journalEntryItems: true }
  });

  if (!original) {
    throw new Error(`Cannot reverse entry: ${originalEntryNumber} not found.`);
  }

  // Swap Debits and Credits
  const reversedEntries = original.journalEntryItems.map(item => ({
    accountId: item.accountId,
    debit: item.credit, // Swap
    credit: item.debit, // Swap
    description: `REVERSAL: ${item.description || ''}`,
  }));

  const now = date || new Date();
  const newEntryNumber = await generateUniqueEntryNumber(tx, now);

  const je = await tx.journalEntry.create({
    data: {
      entryNumber: newEntryNumber,
      date: now,
      reference: `REVERSAL-${original.entryNumber}`,
      note: reason,
      source: 'MANUAL_ADJUSTMENT',
      isAutoGenerated: true,
      journalEntryItems: {
        create: reversedEntries
      }
    },
    include: { journalEntryItems: true }
  });

  // Update Account Balances (Reversed)
  for (const entry of reversedEntries) {
    const account = await tx.chartOfAccount.findUnique({ where: { id: entry.accountId } });
    if (!account) continue;

    let balanceChange = 0;
    if (['ASSET', 'EXPENSE', 'COGS'].includes(account.type)) {
      balanceChange = entry.debit - entry.credit;
    } else {
      balanceChange = entry.credit - entry.debit;
    }

    if (balanceChange !== 0) {
      const updated = await tx.chartOfAccount.update({
        where: { id: entry.accountId },
        data: { balance: { increment: balanceChange } }
      });
      
      const rounded = Math.round(updated.balance * 100) / 100;
      if (updated.balance !== rounded) {
        await tx.chartOfAccount.update({
          where: { id: entry.accountId },
          data: { balance: rounded }
        });
      }
    }
  }

  return je;
}
