'use client';

import { useEffect } from 'react';
import { usePathname } from 'next/navigation';
import { CartProvider } from '@/lib/context/cart-context';
import { WishlistProvider } from '@/lib/context/wishlist-context';
import CartDrawer from '@/components/cart/CartDrawer';
import WishlistDrawer from '@/components/wishlist/WishlistDrawer';
import CartPill from '@/components/cart/CartPill';
import { supabase } from '@/lib/supabase';

// Framer Motion cannot parse Tailwind v4 oklab() colors generated by opacity
// modifiers like bg-black/50. Suppress the non-breaking cosmetic warning globally.
// Also suppress the AuthApiError logged when a stale refresh token is found in
// localStorage — Supabase handles this automatically by firing SIGNED_OUT.
if (typeof window !== 'undefined') {
  const _warn = console.warn.bind(console);
  console.warn = (...args: unknown[]) => {
    if (typeof args[0] === 'string' && args[0].includes('is not an animatable color')) return;
    _warn(...args);
  };

  const _error = console.error.bind(console);
  console.error = (...args: unknown[]) => {
    const msg = typeof args[0] === 'string' ? args[0] : (args[0] instanceof Error ? args[0].message : '');
    if (msg.includes('Invalid Refresh Token') || msg.includes('Refresh Token Not Found')) return;
    _error(...args);
  };
}

export function Providers({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const isAdmin = pathname?.startsWith('/admin');

  // Remember Me enforcement:
  // If user logged in without "Remember Me", sign them out when they open
  // a fresh browser session (sessionStorage is cleared on browser close).
  useEffect(() => {
    const noRemember = localStorage.getItem('no-remember-me') === '1';
    const heartbeat = sessionStorage.getItem('session-heartbeat');
    if (noRemember && !heartbeat) {
      // Browser was reopened — sign out and clean up flag
      supabase.auth.getSession().then(({ data }) => {
        if (data.session) {
          supabase.auth.signOut().then(() => {
            localStorage.removeItem('no-remember-me');
          });
        } else {
          localStorage.removeItem('no-remember-me');
        }
      });
    } else if (heartbeat) {
      // Active tab — refresh heartbeat so navigation within the site doesn't lose it
      sessionStorage.setItem('session-heartbeat', '1');
    }
  }, []);

  return (
    <CartProvider>
      <WishlistProvider>
        {children}
        {!isAdmin && <CartDrawer />}
        {!isAdmin && <WishlistDrawer />}
        {/* Cart pill — right-side floating, visible on all screen sizes */}
        {!isAdmin && <CartPill />}
      </WishlistProvider>
    </CartProvider>
  );
}
