'use client';

import { useEffect } from 'react';
import { usePathname } from 'next/navigation';
import { CartProvider } from '@/lib/context/cart-context';
import { WishlistProvider } from '@/lib/context/wishlist-context';
import CartDrawer from '@/components/cart/CartDrawer';
import WishlistDrawer from '@/components/wishlist/WishlistDrawer';
import CartPill from '@/components/cart/CartPill';
import { supabase } from '@/lib/supabase';

// Framer Motion cannot parse Tailwind v4 oklab() colors generated by opacity
// modifiers like bg-black/50. Suppress the non-breaking cosmetic warning globally.
// Also suppress the AuthApiError logged when a stale refresh token is found in
// localStorage — Supabase handles this automatically by firing SIGNED_OUT.
if (typeof window !== 'undefined') {
  const _warn = console.warn.bind(console);
  console.warn = (...args: unknown[]) => {
    if (typeof args[0] === 'string' && args[0].includes('is not an animatable color')) return;
    _warn(...args);
  };

  const _error = console.error.bind(console);
  console.error = (...args: unknown[]) => {
    const msg = typeof args[0] === 'string' ? args[0] : (args[0] instanceof Error ? args[0].message : '');
    if (msg.includes('Invalid Refresh Token') || msg.includes('Refresh Token Not Found')) return;
    _error(...args);
  };
}

export function Providers({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const isAdmin = pathname?.startsWith('/admin');

  // Remember Me enforcement:
  // If user logged in without "Remember Me", sign them out when they open
  // a fresh browser session (sessionStorage is cleared on browser close).
  useEffect(() => {
    const hasBrowserSession = document.cookie.includes('browser_session=1');
    const hasHeartbeat = sessionStorage.getItem('session-heartbeat');
    const noRemember = localStorage.getItem('no-remember-me') === '1';

    // If both are missing, it's a completely fresh browser start or new tab without cookies
    if (!hasBrowserSession && !hasHeartbeat) {
      supabase.auth.getSession().then(async ({ data }) => {
        if (data.session) {
          let shouldSignOut = noRemember;
          
          if (!shouldSignOut) {
            let isAdmin = false;
            const role = data.session.user?.app_metadata?.app_role;
            if (role === 'admin' || role === 'super_admin') {
              isAdmin = true;
            } else {
              try {
                const res = await fetch('/api/account/role');
                if (res.ok) {
                  const json = await res.json();
                  isAdmin = json.isAdmin;
                }
              } catch(e) {}
            }
            if (isAdmin) shouldSignOut = true;
          }

          if (shouldSignOut) {
            await supabase.auth.signOut();
            localStorage.removeItem('no-remember-me');
          } else {
            document.cookie = "browser_session=1; path=/";
            sessionStorage.setItem('session-heartbeat', '1');
          }
        }
      });
    } else {
      // Session is active, ensure both flags are present
      document.cookie = "browser_session=1; path=/";
      sessionStorage.setItem('session-heartbeat', '1');
    }

    const { data: { subscription } } = supabase.auth.onAuthStateChange((event) => {
      if (event === 'SIGNED_IN') {
        document.cookie = "browser_session=1; path=/";
        sessionStorage.setItem('session-heartbeat', '1');
      } else if (event === 'SIGNED_OUT') {
        document.cookie = "browser_session=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
        sessionStorage.removeItem('session-heartbeat');
        localStorage.removeItem('no-remember-me');
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  return (
    <CartProvider>
      <WishlistProvider>
        {children}
        {!isAdmin && <CartDrawer />}
        {!isAdmin && <WishlistDrawer />}
        {/* Cart pill — right-side floating, visible on all screen sizes */}
        {!isAdmin && <CartPill />}
      </WishlistProvider>
    </CartProvider>
  );
}
